name: MITT ARM Deplyment Demo Version 1.0.0.0

on:
  push: #it will push to main branches and run the workflow automatically
    branches:
      - "main"

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: check code on github repository checking
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # azure cli install
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.7
