name: MITT ARM Deplyment Demo Version 1.0.0.0

on:
  push:
    branches:
      - "main"

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: check code on github repository checking
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}