name: MITT ARM Deplyment Demo Version 1.0.0.0

on:
  push: #it will push to main branches and run the workflow automatically
    branches:
      - "main"

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: check code on github repository checking
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # azure cli install
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az account list -o table

      - name: Check Resource group Information
        run: |
          az group list -o table

      - name: Create Vnet 
        run: |
          az network vnet create --name MITT-github --resource-group github-rg --subnet-name default

      - name: Create Demo VM
        run: |
          az vm create --resource-group github-rg --name MyVM --image UbuntuLTS --admin-username azureuser --generate-ssh-keys --vnet-name MITT-github --subnet default --size Standard_B1s --os-disk-name MyOsDisk --os-disk-size-gb 30 --data-disk-sizes-gb 50
